### PR TITLE
Upgrading solidity-coverage and using new plugin format

### PR DESCRIPTION
**Pull request by justinjmoses**
Fixes coverage reports (thanks to @cgewecke) and adds codecov.io reports via travis

### CODE REVIEW

**Comment by justinjmoses** [comment]
@cgewecke do you happen to have any ideas on the above error with the linker?

**Comment by cgewecke** [comment]
@justinjmoses Will take a look...

**Comment by cgewecke** [comment]
@justinjmoses #453 has some possible fixes....

**Comment by justinjmoses** [comment]
You're a rockstar @cgewecke 🚀. Do you have an address for donations?

**Comment by cgewecke** [comment]
@justinjmoses Oh that's really sweet of you - solidity-coverage 0.7.x was funded by an EF grant and getting it to run on some of the larger, more widely used projects was part of the initial proposal. It's received all the donations it needs, thanks though :)

**Pull request merged**
