### PR TITLE
added transferOwnership functionality in Owned contract

### LINKED ISSUE #582: Owned.sol to include transferOwnership
Right now ownership transfers is a 2 step process
1. nominateNewOwner
2. acceptOwnership

Proposing to add not replace the functionality for `transferOwnership(address _newOwner)` which without nomination or acceptance will transfer the ownership direct to the given address.
This will speed up protocol upgrades when the automated scripts and potentially the delegated migrated can just assign the ownership without the 2 step process.

### PR DESCRIPTION
**Pull request by dev1644**
Resolves #582

### CODE REVIEW

**Comment by justinjmoses** [comment]
@dev1644 Please remove the lockfile change from this PR.

**Comment by dev1644** [comment]
Done @justinjmoses , Removed lock-file but can't run coverage as `Heap out of memory` error popping up. Root cause of the error is coming from Node runtime I searched for some solutions -:

- `export NODE_OPTIONS=--max_old_space_size=4096`, increasing maximum memory available at the run time I was able to run the coverage.

- `buidler --max-memory 4096 coverage --network coverage`, I also search through Builder's issues and found out [this](https://buidler.dev/troubleshooting/common-problems.html#out-of-memory-errors-when-compiling-large-projects). I tried to use this by modifying `coverage npm script` to `"coverage": "buidler --max-memory 4096 coverage --network coverage"`, but it was still breaking.

I also monitor the `node` runtime service executes after starting coverage tests, I noticed at the time compilation of coverage contracts the runtime was consuming 2.8 GB of memory, Default memory cap of `node runtime` is ~1.8 GB, so that might be causing the problem.

**Comment by zyzek** [comment]
Node is allocated more memory for coverage now, so if you merge from `develop` this should be resolved.

https://github.com/Synthetixio/synthetix/blob/bf1c38fef3e6a82fffc07aed835a1049dea9cc3c/package.json#L11

**Comment by justinjmoses** [comment]
Thanks @dev1644 however we need to discuss this issue more thoroughly before accepting any fixes to it (please see my comment on the issue). I am closing this for now but we can reopen in the future if need be.

**Pull request closed without merging**
