### PR TITLE
Atomic uniswap synthetix convert

### PR DESCRIPTION
**Pull request by zyfrank**

### CODE REVIEW

**Comment by jacko125** [comment]
@zyfrank  Why did we create a new pull request to beta and the previous PR was to master branch ?

**Comment by zyfrank** [comment]
@jacko125 two reasons
1  test work are done on rinkby network
2 master branch does not update from bytes4 to bytes32

**Comment by jacko125** [comment]
> @jacko125 two reasons
> 1 test work are done on rinkby network
> 2 master branch does not update from bytes4 to bytes32

@zyfrank  Thanks ! That makes sense. 

I created a new sETH Rinkeby Exchange that points to the sETH ProxyERC20 contract (so it wont need to be upgraded again if we create a new synth and matches what's in our mainnet environment now). 

The new token details are: 

```'0xA83AbFdC9E8Ee990C3C6C0f56a4B06e0faAd583C': {
      [NAME]: 'Synth sETH',
      [SYMBOL]: 'sETH',
      [DECIMALS]: 18,
      [EXCHANGE_ADDRESS]: '0x431295890a123c1542bc85f796fe3baf80dc0e25'
    },```

Would you have a chance to check the atomic_swap exchange function still working as expected? 

I tried swapping to XAU Gold Synth and got a `require` failure in the following txn. I think the atomic swap contract would need to be updated to support the new Synth's that are using the SynthetixProxy and FeePoolProxy since the bytes32 release. 
   
https://rinkeby.etherscan.io/tx/0x1391743da0ce8eddd9489ce6cf44678a877b17abc378919580bcc4c599ff5782

**Comment by zyfrank** [comment]
Hi @jacko125<https://github.com/jacko125>

Can you send your local tokens.js to me ?

________________________________
发件人: Jackson <notifications@github.com>
发送时间: 2019年10月14日 3:57
收件人: Synthetixio/synthetix <synthetix@noreply.github.com>
抄送: zyfrank <zy_frank@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [Synthetixio/synthetix] Atomic uniswap synthetix convert (#253)


@jacko125<https://github.com/jacko125> two reasons
1 test work are done on rinkby network
2 master branch does not update from bytes4 to bytes32

@zyfrank<https://github.com/zyfrank> Thanks ! That makes sense.

I created a new sETH Rinkeby Exchange that points to the sETH ProxyERC20 contract (so it wont need to be upgraded again if we create a new synth and matches what's in our mainnet environment now).

The new token details are:

      [NAME]: 'Synth sETH',
      [SYMBOL]: 'sETH',
      [DECIMALS]: 18,
      [EXCHANGE_ADDRESS]: '0x431295890a123c1542bc85f796fe3baf80dc0e25'
    },```

Would you have a chance to check the atomic_swap exchange function still working as expected?

I tried swapping to XAU Gold Synth and got a `require` failure in the following txn. I think the atomic swap contract would need to be updated to support the new Synth's that are using the SynthetixProxy and FeePoolProxy since the bytes32 release.

https://rinkeby.etherscan.io/tx/0x1391743da0ce8eddd9489ce6cf44678a877b17abc378919580bcc4c599ff5782


―

**Comment by jacko125** [comment]
@zyfrank  https://github.com/Synthetixio/uniswap-frontend/blob/synthetix_uniswap_atomic_swap/src/contexts/Tokens.js

The tokens.js is on this branch on our uniswap-frontend fork

**Comment by zyfrank** [comment]
@jacko125 any progress？

**Comment by jacko125** [comment]
> @jacko125 any progress？

@zyfrank  I tested this yesterday and made a swap on rinkeby via the Uniswap frontend.

**Comment by zyfrank** [comment]
@jacko125 about the price slippage, what I understand is :
1 in original uniswap,  price slippage means that : after current exchange Tx (which will cause liqidity change in uniswap exchange, which cause price change),  change of price of current token<->ETH, it does not mean charged fee

2 so in our case, just present the price slippage of  sETH<--> ETH,   because following sETH<->Synths exchange does not apply to this concept

**Comment by zyfrank** [comment]
@jacko125 I notice you provide 19sETh 19 ETH liquidity in uniswap exchange.  If you input a bigger ether value( for example 2, 3 ethers ), you will meet with a bigger slippage

**Comment by jacko125** [comment]
@zyfrank  Correct, the other older sETH rinkeby pool had a small amount of sETH / ETH (1 or 2) , so the slippage was always too large to test with. I created a larger one pointing to the sETH Proxy contract with 19 sETH / 19ETH, which we can add more overtime.

**Comment by jacko125** [comment]
@zyfrank  I've created a new branch atomic_uniswap_merge based off beta branch for this PR. Could you please update and check tests are passing before we merge AtomicSynthetixUniswapConverter.sol into synthetix repo?

**Comment by zyfrank** [comment]
@jacko125  a new PR (with test fixed) target at branch atomic_uniswap_merge is at https://github.com/Synthetixio/synthetix/pull/292

**Pull request closed without merging**
