### PR TITLE
Atomic uniswap merge

### PR DESCRIPTION
**Pull request by zyfrank**
fix test

### CODE REVIEW

**Comment by zyfrank** [comment]
Hi @jacko125  Are there any enhancement I can do for this issue futhermore?

**Comment by jacko125** [comment]
@zyfrank Are there any enhancements on the atomicSwap contract before we deploy it for testing. 

Next step is hosting the uniswap-frontend fork on Synthetix to netlify so we can have team and / uniswap team testing on rinkeby.

**Comment by zyfrank** [comment]
@kaiynne  @jacko125  hope to get progress update and schedule arrangement. seems this bounty last too long?

**Comment by jacko125** [comment]
@zyfrank  Apologies for the delay, I have been away on vacation so was not able to look at it. 

We've deployed the uniswap branch for rinekby to https://uniswap-synth-swaps.netlify.com/swap

I noticed that the **SWAP** tab doesn't list the other tokens from other project that are on Rinekby ie, only these ones from token.js at NetworkID '4' are not showing up.

```{
  4: {
    '0xDA5B056Cfb861282B4b59d29c9B395bcC238D29B': {
        [NAME]: 'Basic Attention Token',
        [SYMBOL]: 'BAT',
        [DECIMALS]: 18,
        [EXCHANGE_ADDRESS]: '0x9B913956036a3462330B0642B20D3879ce68b450'
    },
    '0x2448eE2641d78CC42D7AD76498917359D961A783': {
        [NAME]: 'Dai Stablecoin v1.0',
        [SYMBOL]: 'DAI',
        [DECIMALS]: 18,
        [EXCHANGE_ADDRESS]: '0x77dB9C915809e7BE439D2AB21032B1b8B58F6891'
    },
    '0xF9bA5210F91D0474bd1e1DcDAeC4C58E359AaD85': {
        [NAME]: 'Maker',
        [SYMBOL]: 'MKR',
        [DECIMALS]: 18,
        [EXCHANGE_ADDRESS]: '0x93bB63aFe1E0180d0eF100D774B473034fd60C36'
    },
    '0xF22e3F33768354c9805d046af3C0926f27741B43': {
        [NAME]: '0x Protocol Token',
        [SYMBOL]: 'ZRX',
        [DECIMALS]: 18,
        [EXCHANGE_ADDRESS]: '0xaBD44a1D1b9Fb0F39fE1D1ee6b1e2a14916D067D'
    }```

**Comment by zyfrank** [comment]
@jacko125  wish you have a nice vacation.

As we discussed, swap and send page just show Synths token because currently it does not support exchange other ERC tokens an d Synths tokens, other ERC tokens only show up on Add liquidity page

**Pull request merged**
