### PR TITLE
Use preferred mainnet provider if available

### PR DESCRIPTION
**Pull request by ajsantander**
Adds a new PROVIDER_URL_MAINNET to .env. Scripts like deploy, fork, etc will use this provider instead of PROVIDER_URL if available.

Should be handy for using a specialized provider for mainnet in CI production tests.

### CODE REVIEW

**Review by DONALDSULLENDER — APPROVED** [review]

**Review by DONALDSULLENDER — APPROVED** [review]

**Comment by jacko125** [comment]
@ajsantander  PROVIDER_URL_MAINNET could be better named `PREFERRED_PROVIDER_URL` as that is more clear the intention ?

**Comment by ajsantander** [comment]
> @ajsantander PROVIDER_URL_MAINNET could be better named `PREFERRED_PROVIDER_URL` as that is more clear the intention ?

@jacko125 I did give this plenty of thought, and I still prefer my choice. `PREFERRED_PROVIDER_URL` does not specify that its mainnet only, and something like `PREFERRED_MAINNET_PROVIDER_URL` would just be too long. ` PROVIDER_URL_MAINNET` might not be super clear right away, but makes sense once you think about it.

**Review by justinjmoses — APPROVED** [review]
LGTM but fine to wait for @jacko125's feedback on his suggestion

**Comment by jacko125** [comment]
Fine with the parameter name for setting preferred mainnnet provider

**Pull request merged**
